### PR TITLE
Django 2.1 support

### PR DESCRIPTION
**Pull request by okihus**
Hi Michael,

Thank you for handy app. I managed to make it work for Django 2.1 
Here is my suggested edits as a pull request.

### CODE REVIEW

**Comment by michaelbrooks** [comment]
Very cool, thanks for the contribution! Can you update the Readme to state which versions of Django are now supported, and if there are any changes to the explanations about migrations?

**Comment by gonzigaran** [comment]
hello can this pull request be solved? I am seeing that this project serves me a lot and I would like to take it up and update it to work with python 3 and make some improvements

**Comment by michaelbrooks** [comment]
I was looking for a few more changes from the author, but they never wrote back. You are welcome to take it over as far as I'm concerned.

**Comment by gonzigaran** [comment]
Great, i will take this ideea over and make support to django 3

**Pull request closed without merging**
